package evolution.stream;

import java.util.stream.Stream;

import org.junit.Test;

public class Iterate {
	@Test
	public void test() {
		// The nth element is generated by the n-1th element by the function f.
		Stream.iterate(0, x -> x + 1).limit(10).forEach(System.out::println);// Only 10 elements will be printed.
		// Skip the first 100 elements and keep 2 candidates.
		Stream.iterate(0, x -> x + 2).skip(100).limit(2).forEach(System.out::println);
		// Get the first 10 even numbers.
		Stream.iterate(0, x -> x + 1).filter(x -> x % 2 == 0).limit(10).forEach(System.out::println);
		// For Counterpart
		for (int i = 0; i < 10; i++) {
			System.out.println(i);
		}
		Stream.iterate(0, x -> x + 1).limit(10).forEach(System.out::println);
	}
}
